### PR TITLE
Fixed it for 16.4

### PR DESCRIPTION
**Pull request by Arzumify**

### CODE REVIEW

**Comment by ghost** [comment]
That's a nightly build which is a moving target and is currently broken on 16.3.1 rootful for example. It doesn't work well on 16.4b2 and above anyway (rootful will overheat your device due to constant daemon crashes and 100% CPU usage, and rootless just won't work unless you use sinject). A proper release will be made when it's ready.

**Comment by claration** [comment]
Imagine

**Comment by Arzumify** [comment]
Flower literally told me to

**Comment by Arzumify** [comment]
Damn you!

**Comment by claration** [comment]
trolled so hard

**Pull request closed without merging**
