### PR TITLE
Change Palen1x iso name & update alpine linux repositories

### PR DESCRIPTION
**Pull request by HyperNotZyper**

### CODE REVIEW

**Comment by HyperNotZyper** [comment]
🧍

**Comment by claration** [comment]
I'll merge this when a new palera1n update is available, just not now.

**Comment by HyperNotZyper** [comment]
> I'll merge this when a new palera1n update is available, just not now.

Ok👍

**Comment by HyperNotZyper** [comment]
uh oh

**Comment by azaz0322** [comment]
did you make sure those repositories and download links actually work instead of just blindly changing the version name?

**Comment by HyperNotZyper** [comment]
> did you make sure those repositories and download links actually work instead of just blindly changing the version name?

yes i did

**Comment by azaz0322** [comment]
> > did you make sure those repositories and download links actually work instead of just blindly changing the version name?
> 
> yes i did

thats surprising its not everyday you see someone testing something before pr'ing it

**Comment by Arcastle** [comment]
Para cuando la version que soporte IOS 16.4 por favro.

**Comment by ainaracatgirl** [comment]
> Para cuando la version que soporte IOS 16.4 por favro.

ES: El equipo esta trabjando en ello, dadles tiempo
EN: The team is working on it, give them time

**Pull request merged**
